/*
 * File: app/store/MyStore.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define( 'MyApp.store.MyStore', {
	extend : 'Ext.data.Store',
	requires : [
		'MyApp.model.MyModel'
	],
	constructor : function ( cfg ) {
		var me = this;
		cfg = cfg || {};
		me.callParent( [
			Ext.apply( {
				model : 'MyApp.model.MyModel',
				storeId : 'MyStore'
			}, cfg )
		] );
	}
} );
var store = Ext.create( 'Ext.data.TreeStore', {
	autoLoad : true,
	proxy : {
		type : 'ajax',
		url : '/DMW/api/getTableList',
		params : {
			treeNode : 'SCM'
		},
		reader : {
			type : 'json'
		},
		timeout : 120000
	},
	root : {
		expanded : true
	}
} );

var dataStore = Ext.create( 'Ext.data.Store', {
	// pageSize : 100,
	defaultPageSize : null,
	model : 'MyApp.model.MyModel1',
	remoteSort : true,
	autoLoad : false,
	remoteFilter : true,
	autoDestroy : false,
	proxy : {
		// load using script tags for cross domain, if the data
		// in on the same
		// domain as
		// this page, an HttpProxy would be better
		autoSave : false,
		autoSync : false,
		// url : '/DMW/api/getTableDetails',
		type : 'ajax',
		method : 'GET',
		timeout : 3000000,
		api : {
			create : '/DMW/api/saveTableDetails?create=true',
			read : '/DMW/api/getTableDetails',
			update : '/DMW/api/saveTableDetails?create=false',
			destroy : '/DMW/api/deleteTableData'
		},
		reader : {
			type : 'json',
			rootProperty : 'data',
			// successProperty : false,
			totalProperty : 'totalCount'
		},
		// sends single sort as multi parameter
		simpleSortMode : true,
		listeners : {
			update : function ( thisStore, record, operation ) {
				console.log( 'Update happened' );
				console.log( record );
				console.log( operation );
			},
			success : function () {
				console.log( 'Save happened' );
			},
			remove : function () {
				console.log( "Record removed" );
			},
			exception : function ( proxy, response, operation ) {
				var jason = Ext.util.Format.htmlDecode( response.responseText );
				console.log( jason );
				Ext.Msg.alert( 'Exception', jason );

			}
		}
	}
} );
var confStore = Ext.create( 'Ext.data.Store', {
	model : 'SIMPLE_COMBO',
	autoLoad : true,
	proxy : {
		type : 'ajax',
		url : '/DMW/api/getConfList',
		paramsAsHash : true,
		timeout : 3000000,
		method : 'GET',
		reader : {
			type : 'json',
			// root : 'result',
			idProperty : 'name'
		},
		extraParams : {
			query : ''
		}
	}
} );

var rolesStore = Ext.create( 'Ext.data.Store', {
	model : 'SIMPLE_COMBO',
	autoLoad : true,
	proxy : {
		type : 'ajax',
		url : '/DMW/api/getRolesList',
		paramsAsHash : true,
		method : 'GET',
		timeout : 3000000,
		reader : {
			type : 'json',
			// root : 'result',
			idProperty : 'name'
		},
		extraParams : {
			query : ''
		}
	}
} );
var schemaStore = Ext.create( 'Ext.data.Store', {
	model : 'SIMPLE_COMBO',
	autoLoad : true,
	proxy : {
		type : 'ajax',
		url : '/DMW/api/getTableOwners',
		paramsAsHash : true,
		method : 'GET',
		timeout : 3000000,
		reader : {
			type : 'json',
			idProperty : 'name'
		}
	}
} );
var tableStore = Ext.create( 'Ext.data.Store', {
	model : 'SIMPLE_COMBO',
	autoLoad : true,
	proxy : {
		type : 'ajax',
		url : '/DMW/api/getTablesList',
		paramsAsHash : true,
		method : 'GET',
		timeout : 3000000,
		reader : {
			type : 'json',
			idProperty : 'name'
		},
		extraParams : {
			query : '',
			tableName : '',
			owner : ''
		}
	}
} );
var columnStore = Ext.create( 'Ext.data.Store', {
	model : 'SIMPLE_COMBO',
	autoLoad : false,
	proxy : {
		type : 'ajax',
		url : '/DMW/api/getColumnsList',
		paramsAsHash : true,
		method : 'GET',
		timeout : 3000000,
		reader : {
			type : 'json',
			idProperty : 'name'
		}
	}
} );

var editColumnStore = Ext.create( 'Ext.data.Store', {
	model : 'SIMPLE_COMBO',
	autoLoad : false,
	proxy : {
		type : 'ajax',
		url : '/DMW/api/getEditColumnsList',
		paramsAsHash : true,
		method : 'GET',
		timeout : 3000000,
		reader : {
			type : 'json',
			idProperty : 'name'
		},
		extraParams : {
			owner : '',
			tableName : ''
		}
	}
} );