

CREATE TABLE I2WEBDATA.AUDIT_TRAIL
(
  AUDIT_TRAIL_ID     NUMBER,
  EVENT_NAME         VARCHAR2(200 BYTE),
  EVENT_DESCRIPTION  VARCHAR2(2000 BYTE),
  OLD_VALUE          VARCHAR2(200 BYTE),
  NEW_VALUE          VARCHAR2(200 BYTE),
  UPDATED_BY         VARCHAR2(200 BYTE),
  UPDATE_DATE        DATE
)
;

--  There is no statement for index I2WEBDATA.SYS_C003079141.
--  The object is created when the parent object is created.

ALTER TABLE I2WEBDATA.AUDIT_TRAIL ADD (
  PRIMARY KEY
  (AUDIT_TRAIL_ID))
 ;

GRANT ALL ON I2WEBDATA.AUDIT_TRAIL TO I2WEB;
